import Head from 'next/head'
import { Inter } from 'next/font/google'
import { useState } from 'react'
import { IconButton } from '@mui/material'
import SearchIcon from '@mui/icons-material/Search';
import Button from '@mui/material/Button';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [cityName, setCityName] = useState('')
  const [state, setState] = useState('')

  const searchForWeather = () => {
    fetch(`https://api.hgbrasil.com/weather?key=SUA-CHAVE&city_name=${cityName},${state}`)
      .then((response) => response.json())
      .then((data) => console.log(data))
  }


  return (
    <>
      <Head>
        <title>Aplicação para Busca de Clima</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section>
        <input type="text" placeholder='Cidade' value={cityName}
          onChange={(e: React.FormEvent<HTMLInputElement>) => setCityName(e.currentTarget.value)}
        />
        <input type="" placeholder='Estado' value={state}
          onChange={((e: React.FormEvent<HTMLInputElement>) => setState(e.currentTarget.value))}
        />
        <Button onClick={searchForWeather}>
          Buscar
        </Button>
      </section>

    </>
  )
}
