import React from 'react'
import Head from 'next/head'
import { Inter } from 'next/font/google'
import { useState } from 'react'
import { Box, Typography, IconButton, Input, MenuItem, Select, SelectChangeEvent, TextField } from '@mui/material'
import SearchIcon from '@mui/icons-material/Search';
import Button from '@mui/material/Button';
import { brazilStates } from '@/utils/constants';
import SearchBar from '@/components/searchbar';
import HomeStyles from '../styles/Home.module.css'
import WeatherBox from '@/components/box'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [cityName, setCityName] = useState<string>('')
  const [state, setState] = useState<string>('')

  const [weatherInfo, setWeatherInfo] = useState()

  const onChangeCity = (e: React.ChangeEvent<HTMLInputElement>) => {
    setCityName(e.currentTarget.value)
  }

  const onChangeState = (event: SelectChangeEvent) => {
    setState(event.target.value)
  }

  const searchForWeather = () => {
    fetch(`https://api.hgbrasil.com/weather?key=SUA-CHAVE&city_name=${cityName},${state}`)
      .then((response) => response.json())
      .then((data) => setWeatherInfo(data))

    console.log(weatherInfo)
  }


  return (
    <Box className={HomeStyles.main}>
      <Head>
        <title>Aplicação para Busca de Clima</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <WeatherBox
        cityName={cityName}
        onChangeCity={onChangeCity}
        onChangeState={onChangeState}
        searchForWeather={searchForWeather}
      >
        <Typography variant='h5'>Funcionou o Children</Typography>
      </WeatherBox>
      {JSON.stringify(weatherInfo) ?? <h2>Informe a cidade e estado para buscarmos o clima</h2>}
    </Box>
  )
}
